services:

  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    networks:
      - Academy-app

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - Academy-app
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    container_name: frontend
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - Academy-app

volumes:
  data: {}
networks:
  Academy-app: