sonar.projectKey=idavidkhan_Academy-app-DevOps_3307f86d-7cf0-49e9-8b39-71bd89329a7f
sonar.projectName=Academy-app-DevOps
sonar.sources=Frontend,backend
sonar.exclusions=**/node_modules/**,**/vendor/**,**/*.test.js,**/dist/**,**/build/**